### ISSUE TITLE
Offline vehicles don't sync to the Apple Watch

### ISSUE THREAD

**Issue by ardez73** [ElectricSidecar/ElectricSidecar#16]
I'm trying to connect my apple watch SE 2022 to my iPhone 13 pro max but no success. Behaviour is inconsistent. Sometimes the sync button is available, sometimes not. When it is, on watch screen I only see a quick glitch but nothing happens. I understand this is not a priority...;-)

**Comment by electricsidecaradmin** [comment]
Can you share a screenshot or photo of your watch to support@electricsidecar.app? Which OS version is your watch running?

One thing to note is that Apple Watch support with OBD-based vehicles is somewhat limited right now. Cloud syncing of OBD data will be coming in a future release of Electric Sidecar, which will improve the utility of solely OBD-based vehicles.

**Comment by ardez73** [comment]
Latest public betas on iOS and WatchOS. There's not much to share, since nothing changes on the Watch screen, except that "glitch" I notice when I press the sync account button on iphone.

**Comment by electricsidecaradmin** [comment]
Are you trying to sync an offline vehicle to the watch?

**Comment by ardez73** [comment]
yes

**Comment by electricsidecaradmin** [comment]
Offline vehicles don't sync to the watch yet because once synced to the watch they won't show much information until cloud sync is built out. This might explain the glitchy behavior you're seeing.

That being said, I can see how this behavior is confusing as-is, so I'll treat this as a feature request to get offline vehicles to sync to the watch.

**Comment by ardez73** [comment]
Sweet. Thank you.

**Comment by electricsidecaradmin** [comment]
![Simulator Screenshot - Apple Watch Series 9 (41mm) - 2024-05-26 at 12 51 38](https://github.com/ElectricSidecar/ElectricSidecar/assets/170385585/05697c26-6c36-4c0f-90ee-80ae78204fca)

Offline vehicles now sync along with connected and simulated accounts :)

**Comment by electricsidecaradmin** [comment]
This will go out in v1.13.
