### ISSUE TITLE
Wrong Avg consumption graph

### ISSUE THREAD

**Issue by Bluearrow75** [ElectricSidecar/ElectricSidecar#21]
I noticed that the average consumption graph in the home page doesn’t highlight the correct consumption of the latest trip

**Comment by Bluearrow75** [comment]
Happy to share a screenshot but I am not sure how to do it

**Comment by electricsidecar-dev** [comment]
Send a screenshot to support@electricsidecar.app please and I will look into it!

**Comment by Bluearrow75** [comment]
Hi Jeff

Bayou can find below the screenshot you requested

As you see the last trip consumption was 22kwh/100km and what is
highlighted in the graph is different.

Thank you





Sent from Gmail for iPhone


Le dim. 23 juin 2024 à 13:00, Electric Sidecar ***@***.***> a
écrit :

**Comment by electricsidecar-dev** [comment]
Does it still show the wrong highlight if you tap the refresh button on your vehicle?

**Comment by Bluearrow75** [comment]
Yes…
- I tried that button. The other data is refreshing (but not the latest
trip on the histogram)
- I tried to force refresh through a scroll down as well
- I tried relaunching the app
- I just did a new trip of 100 km. The histogram updated the number of
trips under 20-22kwh category but that bar is not highlighted as the one
used for the latest trip.

So in conclusion the histogram seems to be getting updated in terms of
number of trips but not the highlight of the latest trip.


Sent from Gmail for iPhone


Le dim. 23 juin 2024 à 18:47, Electric Sidecar ***@***.***> a
écrit :

**Comment by electricsidecar-dev** [comment]
Confirmed this bug locally. Fix has landed and will go out in the next release.

<img width="380" alt="Screenshot 2024-06-23 at 10 24 06 PM" src="https://github.com/ElectricSidecar/ElectricSidecar/assets/170385585/c2aaa5bb-adec-42d1-b343-ecd090895f36">
