### ISSUE TITLE
Two entries for my car in the “Garage”

### ISSUE THREAD

**Issue by Alan-Burgess** [ElectricSidecar/ElectricSidecar#22]
I have two entries for my car with different names in the “Garage” section, the data appears identical. Unable to find a way of deleting one of them. I have setup ODB, I’m unsure if that has anything to do with it.

**Comment by electricsidecar-dev** [comment]
Do you see two cars in Settings > Vehicles & accounts ?

**Comment by Alan-Burgess** [comment]
I do have an “Offline vehicle” and a “Porsche” entry.On 25 Jun 2024, at 18:11, Electric Sidecar ***@***.***> wrote:﻿
Do you see two cars in Settings > Vehicles & accounts ?

**Comment by electricsidecar-dev** [comment]
If the offline vehicle's VIN matches your Porsche, you. Can swipe to delete the offline vehicle account and you should see the duplicate go away.

**Comment by jverkoey** [comment]
Marking as closed because the resolution here is likely to remove the self-managed/offline vehicle in favor of the account-managed one.
