### ISSUE TITLE
Apple Watch app crashes when syncing accounts

### ISSUE THREAD

**Issue by martbock** [ElectricSidecar/ElectricSidecar#24]
When I try to sync my MG account to my watch, the app on the watch immediately crashes.

**Comment by jverkoey** [comment]
Thank you for the report! Looking into this now.

**Comment by jverkoey** [comment]
Which model of Apple Watch are you running?

**Comment by jverkoey** [comment]
Looks like the crash was likely due to https://jeffverkoeyen.com/blog/2024/10/02/arm64_32-PSA/.

I've fixed the error and the fix will go out in the next Sidecar release.
