### ISSUE TITLE
Hybrid state of charge widget visual glitch

### ISSUE THREAD

**Issue by zaaaacch** [ElectricSidecar/ElectricSidecar#26]
https://github.com/user-attachments/assets/927823d7-3c3a-4b39-9be5-9260381bf73c
The video above shows that when SoC / fuel level is 100%, the text causes the bars to shorten

**Comment by jverkoey** [comment]
Thanks for reporting! Added this to tasks for the next Sidecar release.

**Comment by jverkoey** [comment]
Fixed! Will go out in the next release.
